### ISSUE TITLE
Problem with Loading from Server

### ISSUE THREAD

**Issue by jagroop** [IvanAquino/adonis-vuetify-starter#1]
Hi, @IvanAquino thanks for the awesome package. :+1: 

I am facing a problem with server loading.
Actually, I have enabled vue router mode ```history```

```javascript
let router = new VueRouter({
    mode: 'history'
})
```

When i hard refresh the page, system checks for adonis routes

![screenshot from 2018-04-16 21-48-22](https://user-images.githubusercontent.com/12444128/38822068-f756ae54-41bf-11e8-93e7-04f3b2606725.png)

Is there anything I could do to fix it.

Thanks

**Comment by jagroop** [comment]
Fixed !

```javascript
// start/routes.js

Route.on('*').render('frontend')

```

**Comment by IvanAquino** [comment]
Thanks for the feedback, I added this to the Readme

**Comment by jagroop** [comment]
Hi @IvanAquino After enabling mode history.
Now i am facing CSRF token exception ... so Login reg. No longer working.
If i  disable CSRF, it bypasses the login / registration both ( Doesn't check API routes) .

Thanks.

**Comment by IvanAquino** [comment]
I think is not csrf exception, i was use request.url un the frontend.edge but with history mode that print relative path /login for example but i  need / path, un the last commit i included a global method to print absolute route check it

**Comment by jagroop** [comment]
The problem was : I was adding this route at the beginning of file

```javascript
Route.any('*', ({ view }) => view.render('frontend'))
```
Had to read the readme again.

I am using this package in my next project. :fire: 

Sorry for the false alarm. And thanks for the help
